#ifndef LOGGER_APPENDERS_H_
#define LOGGER_APPENDERS_H_

#define DEVELOPER_APPENDER_ID              L"DEVELOPER"
#define ATM_MANAGER_APPENDER_ID            L"ATM_MANAGER"
#define DEVICE_MANAGER_APPENDER_ID         L"DEVICE_MANAGER"
#define WEB_ATM_APPENDER_ID                L"WEB_ATM"
#define COMMUNICATION_APPENDER_ID          L"COMMUNICATION"
#define ELECTRONIC_JOURNAL_APPENDER_ID     L"ELECTRONIC_JOURNAL"
#define RAHSAM_APPENDER_ID                 L"RAHSAM"
#define SUPERVISOR_APPENDER_ID             L"SUPERVISOR"
#define SUPERVISOR_PASSIVE_APPENDER_ID     L"SUPERVISOR_PASSIVE"
#define OPERATOR_APPENDER_ID               L"OPERATOR"
#define PROCESS_APPENDER_ID                L"PROCESS"
#define PERFORMANCE_STATISTICS_APPENDER_ID L"PERFORMANCE_STATISTICS"

#endif // LOGGER_APPENDERS_H_
